name: 'Strands Agent Runner'
description: 'Execute a Strands agent with the given prompts and configuration'
inputs:
  system_prompt:
    description: 'System prompt for the agent'
    required: true
  session_id:
    description: 'Session ID for the agent execution'
    required: true
  task_prompt:
    description: 'Task prompt for the agent'
    required: true
  aws_role_arn:
    description: 'AWS IAM role ARN for authentication'
    required: true
  sessions_bucket:
    description: 'S3 bucket for session storage'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: '.github/scripts/requirements.txt'

    - name: Install Strands Agents
      shell: bash
      run: |
        echo "📦 Installing from requirements.txt"
        uv pip install --system -r .github/scripts/requirements.txt --quiet

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "Strands Agent"
        git config --global user.email "217235299+strands-agent@users.noreply.github.com"
        git config --global core.pager cat
        PAGER=cat

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        role-session-name: GitHubActions-StrandsAgent-${{ github.run_id }}
        aws-region: us-west-2
        mask-aws-account-id: true

    - name: Execute strands command
      shell: bash
      env:
        # GitHub Configuration
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_ACTOR: ${{ github.actor }}

        # Task Configuration
        INPUT_TASK: ${{ inputs.task_prompt }}
        INPUT_SYSTEM_PROMPT: ${{ inputs.system_prompt }}

        # AWS Configuration
        AWS_REGION: 'us-west-2'

        # Session Manager
        S3_SESSION_BUCKET: ${{ inputs.sessions_bucket }}
        SESSION_ID: ${{ inputs.session_id }}
      run: |
        uv run .github/scripts/agent_runner.py "$INPUT_TASK"
