//! strands-rs — Rust host wrapper for the Strands Agent WASM component.
//!
//! Provides a high-level [`Agent`] API backed by a persistent WASM component.
//! The agent maintains conversation history across calls to [`Agent::stream`]
//! and [`Agent::invoke`].

use std::collections::HashMap;

use anyhow::{Context, Result};
use wasmtime::component::{Component, HasSelf, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};
use wasmtime_wasi_http::{WasiHttpCtx, WasiHttpView};

/// Generated by `wasmtime::component::bindgen!` from `wit/agent.wit`.
///
/// Produces Rust types/traits mirroring every WIT record, enum, variant, and
/// resource. The `strands_derive::Export` derive on each type additionally
/// generates `{Name}_` wrapper structs (gated behind `pyo3`/`uniffi` features)
/// for FFI-friendly flat representations, plus `From<Name> for Name_` impls.
mod bindings {
    wasmtime::component::bindgen!({
        path: "../wit",
        world: "agent",
        exports: { default: async },
        additional_derives: [strands_derive::Export],
    });
}

pub use bindings::strands::agent::types::{
    AnthropicConfig, BedrockConfig, MetadataEvent, Metrics, ModelConfig, ModelParams, StopData,
    StopReason, StreamEvent, ToolResultEvent, ToolSpec, ToolUseEvent, Usage,
};

/// Auto-generated wrapper types (available with `pyo3` or `uniffi` features).
/// Each *_ type implements `From<WitType>` for zero-boilerplate conversion.
#[cfg(any(feature = "pyo3", feature = "uniffi"))]
pub use bindings::strands::agent::types::{
    MetadataEvent_, Metrics_, StopData_, StopReason_, StreamEvent_, ToolResultEvent_, ToolSpec_,
    ToolUseEvent_, Usage_,
};

#[cfg(feature = "pyo3")]
pub mod python;

#[cfg(feature = "uniffi")]
uniffi::setup_scaffolding!();

use bindings::strands::agent::types::AgentConfig as WitAgentConfig;

pub use wasmtime::component::ResourceAny;

/// A function that dispatches tool calls from the guest.
/// Receives `(tool_name, input_json, tool_use_id)` and returns `Ok(result_json)` or `Err(error_message)`.
type ToolHandlerFn = Box<dyn Fn(&str, &str, &str) -> Result<String, String> + Send + Sync>;

/// Receives `(level, message, optional_context_json)`.
type LogHandlerFn = Box<dyn Fn(&str, &str, Option<&str>) + Send + Sync>;

struct HostState {
    ctx: WasiCtx,
    http: WasiHttpCtx,
    table: ResourceTable,
    tool_dispatch: Option<ToolHandlerFn>,
    log_handler: Option<LogHandlerFn>,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.ctx,
            table: &mut self.table,
        }
    }
}

impl WasiHttpView for HostState {
    fn ctx(&mut self) -> &mut WasiHttpCtx {
        &mut self.http
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

impl bindings::strands::agent::host_log::Host for HostState {
    fn log(&mut self, entry: bindings::strands::agent::host_log::LogEntry) {
        let level_str = match entry.level {
            bindings::strands::agent::host_log::LogLevel::Trace => "trace",
            bindings::strands::agent::host_log::LogLevel::Debug => "debug",
            bindings::strands::agent::host_log::LogLevel::Info => "info",
            bindings::strands::agent::host_log::LogLevel::Warn => "warn",
            bindings::strands::agent::host_log::LogLevel::Error => "error",
        };
        if let Some(ref handler) = self.log_handler {
            handler(level_str, &entry.message, entry.context.as_deref());
        } else {
            let ctx = entry.context.as_deref().unwrap_or("");
            match level_str {
                "error" => tracing::error!(target: "strands::wasm", "{} {ctx}", entry.message),
                "warn" => tracing::warn!(target: "strands::wasm", "{} {ctx}", entry.message),
                "info" => tracing::info!(target: "strands::wasm", "{} {ctx}", entry.message),
                "debug" => tracing::debug!(target: "strands::wasm", "{} {ctx}", entry.message),
                _ => tracing::trace!(target: "strands::wasm", "{} {ctx}", entry.message),
            }
        }
    }
}

impl bindings::strands::agent::tool_provider::Host for HostState {
    fn call_tool(
        &mut self,
        args: bindings::strands::agent::types::CallToolArgs,
    ) -> Result<String, String> {
        match &self.tool_dispatch {
            Some(dispatch) => dispatch(&args.name, &args.input, &args.tool_use_id),
            None => Err(format!("no handler for tool '{}'", args.name)),
        }
    }

    fn call_tools(
        &mut self,
        args: bindings::strands::agent::types::CallToolsArgs,
    ) -> Vec<Result<String, String>> {
        match &self.tool_dispatch {
            Some(dispatch) => args
                .calls
                .iter()
                .map(|call| dispatch(&call.name, &call.input, &call.tool_use_id))
                .collect(),
            None => args
                .calls
                .iter()
                .map(|call| Err(format!("no handler for tool '{}'", call.name)))
                .collect(),
        }
    }
}

/// Builder for configuring and constructing an [`Agent`].
pub struct AgentBuilder {
    model_config: Option<ModelConfig>,
    model_params: Option<ModelParams>,
    system_prompt: Option<String>,
    system_prompt_blocks: Option<String>,
    tools: Vec<ToolSpec>,
    handlers: HashMap<String, Box<dyn Fn(&str) -> Result<String, String> + Send + Sync>>,
    tool_dispatch: Option<ToolHandlerFn>,
    log_handler: Option<LogHandlerFn>,
    trace_context: Option<String>,
    use_jit: bool,
}

impl AgentBuilder {
    /// Set the model configuration. If not called, defaults to Bedrock.
    pub fn model(mut self, config: ModelConfig) -> Self {
        self.model_config = Some(config);
        self
    }

    /// Set common model tuning parameters (max tokens, temperature, top-p).
    pub fn model_params(mut self, params: ModelParams) -> Self {
        self.model_params = Some(params);
        self
    }

    /// Set the system prompt as a plain string.
    pub fn system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = Some(prompt.into());
        self
    }

    /// Set the system prompt as a JSON array of content blocks.
    pub fn system_prompt_blocks(mut self, blocks: impl Into<String>) -> Self {
        self.system_prompt_blocks = Some(blocks.into());
        self
    }

    /// Register a tool with a name, description, JSON schema, and handler.
    pub fn tool(
        mut self,
        name: impl Into<String>,
        description: impl Into<String>,
        input_schema: serde_json::Value,
        handler: impl Fn(&str) -> Result<String, String> + Send + Sync + 'static,
    ) -> Self {
        let name = name.into();
        self.tools.push(ToolSpec {
            name: name.clone(),
            description: description.into(),
            input_schema: serde_json::to_string(&input_schema).unwrap_or_default(),
        });
        self.handlers.insert(name, Box::new(handler));
        self
    }

    /// Set pre-built tool specs directly (used by FFI wrappers like PyO3).
    pub fn tools(mut self, specs: Vec<ToolSpec>) -> Self {
        self.tools = specs;
        self
    }

    /// Set the W3C traceparent header for distributed tracing propagation.
    pub fn trace_context(mut self, ctx: impl Into<String>) -> Self {
        self.trace_context = Some(ctx.into());
        self
    }

    /// Set a single dispatch function for all tool calls.
    /// Receives `(tool_name, input_json, tool_use_id)`.
    pub fn tool_dispatch_fn(
        mut self,
        f: impl Fn(&str, &str, &str) -> Result<String, String> + Send + Sync + 'static,
    ) -> Self {
        self.tool_dispatch = Some(Box::new(f));
        self
    }

    /// Use JIT compilation instead of the AOT-precompiled component.
    /// Loads `strands-wasm/dist/strands-agent.wasm` directly at runtime.
    /// Slower startup but picks up WASM changes without a Rust rebuild.
    pub fn use_jit(mut self) -> Self {
        self.use_jit = true;
        self
    }

    /// Set a handler for structured log entries from the WASM guest.
    /// Receives `(level, message, optional_context_json)`.
    pub fn log_handler(
        mut self,
        f: impl Fn(&str, &str, Option<&str>) + Send + Sync + 'static,
    ) -> Self {
        self.log_handler = Some(Box::new(f));
        self
    }

    /// Build the agent, loading and instantiating the WASM component.
    pub async fn build(self) -> Result<Agent> {
        let tools: Option<Vec<ToolSpec>> = if self.tools.is_empty() {
            None
        } else {
            Some(self.tools)
        };

        let tool_dispatch = if let Some(dispatch) = self.tool_dispatch {
            Some(dispatch)
        } else if !self.handlers.is_empty() {
            let handlers = self.handlers;
            Some(Box::new(
                move |name: &str, input: &str, _tool_use_id: &str| -> Result<String, String> {
                    match handlers.get(name) {
                        Some(handler) => handler(input),
                        None => Err(format!("unknown tool: {name}")),
                    }
                },
            ) as ToolHandlerFn)
        } else {
            None
        };

        Agent::from_parts(
            self.model_config,
            self.model_params,
            self.system_prompt,
            self.system_prompt_blocks,
            tools,
            tool_dispatch,
            self.log_handler,
            self.trace_context,
            self.use_jit,
        )
        .await
    }
}

/// A Strands agent backed by a WASM component.
///
/// Persists across multiple `stream()` / `invoke()` calls, maintaining
/// conversation history inside the guest component.
///
/// # Example
/// ```no_run
/// # async fn example() -> anyhow::Result<()> {
/// use strands::{Agent, StreamEvent, StopData};
/// use tokio_stream::StreamExt;
///
/// let mut agent = Agent::builder()
///     .system_prompt("You are a helpful assistant. Be concise.")
///     .build()
///     .await?;
///
/// let stream = agent.stream("Hello!").await?;
/// tokio::pin!(stream);
///
/// while let Some(event) = stream.next().await {
///     match event? {
///         StreamEvent::TextDelta(t) => print!("{t}"),
///         StreamEvent::Stop(data) => println!("\n[{:?}]", data.reason),
///         StreamEvent::Error(e) => eprintln!("[error: {e}]"),
///         _ => {}
///     }
/// }
/// # Ok(())
/// # }
/// ```
pub struct Agent {
    store: Store<HostState>,
    instance: bindings::Agent,
    wit_agent: ResourceAny,
}

impl Agent {
    /// Create a builder for configuring an agent.
    pub fn builder() -> AgentBuilder {
        AgentBuilder {
            model_config: None,
            model_params: None,
            system_prompt: None,
            system_prompt_blocks: None,
            tools: Vec::new(),
            handlers: HashMap::new(),
            tool_dispatch: None,
            log_handler: None,
            trace_context: None,
            use_jit: false,
        }
    }

    async fn from_parts(
        model_config: Option<ModelConfig>,
        model_params: Option<ModelParams>,
        system_prompt: Option<String>,
        system_prompt_blocks: Option<String>,
        tools: Option<Vec<ToolSpec>>,
        tool_dispatch: Option<ToolHandlerFn>,
        log_handler: Option<LogHandlerFn>,
        trace_context: Option<String>,
        use_jit: bool,
    ) -> Result<Self> {
        let mut wasm_config = Config::new();
        wasm_config.async_support(true);
        wasm_config.wasm_component_model(true);
        wasm_config.max_wasm_stack(32 * 1024 * 1024);
        wasm_config.async_stack_size(64 * 1024 * 1024);

        let engine = Engine::new(&wasm_config)?;

        let component = if use_jit {
            let wasm_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../strands-wasm/dist/strands-agent.wasm");
            Component::from_file(&engine, &wasm_path)
                .with_context(|| format!("JIT: failed to load {}", wasm_path.display()))?
        } else {
            unsafe {
                Component::deserialize(
                    &engine,
                    include_bytes!(concat!(env!("OUT_DIR"), "/strands-agent.cwasm")),
                )
            }
            .with_context(|| "failed to load precompiled strands component")?
        };

        let mut linker = Linker::<HostState>::new(&engine);
        wasmtime_wasi::p2::add_to_linker_async(&mut linker)?;
        wasmtime_wasi_http::add_only_http_to_linker_async(&mut linker)?;
        bindings::strands::agent::tool_provider::add_to_linker::<HostState, HasSelf<HostState>>(
            &mut linker,
            |state: &mut HostState| state,
        )?;
        bindings::strands::agent::host_log::add_to_linker::<HostState, HasSelf<HostState>>(
            &mut linker,
            |state: &mut HostState| state,
        )?;

        let wasi = WasiCtxBuilder::new().inherit_stdio().inherit_env().build();

        let mut store = Store::new(
            &engine,
            HostState {
                ctx: wasi,
                http: WasiHttpCtx::new(),
                table: ResourceTable::new(),
                tool_dispatch,
                log_handler,
            },
        );

        let instance = bindings::Agent::instantiate_async(&mut store, &component, &linker).await?;

        // The guest is bundled with --platform=browser so the AWS SDK can't
        // resolve credentials from the filesystem or environment. Inject them
        // into the model config so the guest passes them directly to the client.
        let model_config = inject_aws_credentials(model_config);

        let config = WitAgentConfig {
            model: model_config,
            model_params,
            system_prompt,
            system_prompt_blocks,
            tools,
            trace_context,
        };

        let iface = instance.strands_agent_api();
        let wit_agent = iface.agent().call_constructor(&mut store, &config).await?;

        Ok(Self {
            store,
            instance,
            wit_agent,
        })
    }

    /// Stream events from the agent for the given input.
    pub async fn stream(
        &mut self,
        input: &str,
    ) -> Result<impl futures_core::Stream<Item = Result<StreamEvent>> + '_> {
        self.stream_with_options(input, None, None).await
    }

    /// Stream events with per-request tool and tool-choice overrides.
    pub async fn stream_with_options(
        &mut self,
        input: &str,
        tools: Option<Vec<ToolSpec>>,
        tool_choice: Option<String>,
    ) -> Result<impl futures_core::Stream<Item = Result<StreamEvent>> + '_> {
        let Self {
            store,
            instance,
            wit_agent,
        } = self;
        let api = instance.strands_agent_api();
        let args = bindings::exports::strands::agent::api::StreamArgs {
            input: input.to_string(),
            tools,
            tool_choice,
        };
        let handle = api
            .agent()
            .call_generate(&mut *store, *wit_agent, &args)
            .await?;

        Ok(async_stream::stream! {
            loop {
                match api
                    .response_stream()
                    .call_read_next(&mut *store, handle)
                    .await
                {
                    Ok(Some(events)) => {
                        for event in events {
                            yield Ok(event);
                        }
                    }
                    Ok(None) => break,
                    Err(e) => {
                        yield Err(e);
                        break;
                    }
                }
            }
        })
    }

    /// Invoke the agent and collect the full response.
    pub async fn invoke(&mut self, input: &str) -> Result<AgentResult> {
        let Self {
            store,
            instance,
            wit_agent,
        } = self;
        let api = instance.strands_agent_api();
        let args = bindings::exports::strands::agent::api::StreamArgs {
            input: input.to_string(),
            tools: None,
            tool_choice: None,
        };
        let handle = api
            .agent()
            .call_generate(&mut *store, *wit_agent, &args)
            .await?;

        let mut text = String::new();
        let mut stop_data = None;

        while let Some(events) = api
            .response_stream()
            .call_read_next(&mut *store, handle)
            .await?
        {
            for event in events {
                match event {
                    StreamEvent::TextDelta(delta) => text.push_str(&delta),
                    StreamEvent::Stop(data) => stop_data = Some(data),
                    StreamEvent::Error(err) => {
                        return Err(anyhow::anyhow!("agent error: {err}"));
                    }
                    _ => {}
                }
            }
        }

        let stop = stop_data.unwrap_or(StopData {
            reason: StopReason::EndTurn,
            usage: None,
            metrics: None,
        });

        Ok(AgentResult {
            text,
            stop_reason: stop.reason,
            usage: stop.usage,
            metrics: stop.metrics,
        })
    }
}

impl Agent {
    /// Begin a new response stream. Returns a handle for use with [`next_events`].
    pub async fn start_stream(&mut self, input: &str) -> Result<ResourceAny> {
        self.start_stream_with_options(input, None, None).await
    }

    /// Begin a new response stream with per-request tool and tool-choice overrides.
    pub async fn start_stream_with_options(
        &mut self,
        input: &str,
        tools: Option<Vec<ToolSpec>>,
        tool_choice: Option<String>,
    ) -> Result<ResourceAny> {
        let Self {
            store,
            instance,
            wit_agent,
        } = self;
        let api = instance.strands_agent_api();
        let args = bindings::exports::strands::agent::api::StreamArgs {
            input: input.to_string(),
            tools,
            tool_choice,
        };
        api.agent()
            .call_generate(&mut *store, *wit_agent, &args)
            .await
    }

    /// Pull the next batch of events from the stream.
    pub async fn next_events(&mut self, handle: ResourceAny) -> Result<Option<Vec<StreamEvent>>> {
        let api = self.instance.strands_agent_api();
        api.response_stream()
            .call_read_next(&mut self.store, handle)
            .await
    }

    /// Send a response to an interrupt on the given stream.
    pub async fn respond(&mut self, handle: ResourceAny, payload: &str) -> Result<()> {
        let api = self.instance.strands_agent_api();
        let args = bindings::exports::strands::agent::api::RespondArgs {
            payload: payload.to_string(),
        };
        api.response_stream()
            .call_respond(&mut self.store, handle, &args)
            .await
    }

    /// Cancel a running stream.
    pub async fn cancel_stream(&mut self, handle: ResourceAny) -> Result<()> {
        let api = self.instance.strands_agent_api();
        api.response_stream()
            .call_cancel(&mut self.store, handle)
            .await
    }

    /// Drop (destroy) a response-stream resource, releasing WASM-side state.
    pub async fn drop_stream(&mut self, handle: ResourceAny) -> Result<()> {
        handle.resource_drop_async(&mut self.store).await
    }

    /// Get the agent's conversation history as a JSON string.
    pub async fn get_messages(&mut self) -> Result<String> {
        let api = self.instance.strands_agent_api();
        api.agent()
            .call_get_messages(&mut self.store, self.wit_agent)
            .await
    }

    /// Set the agent's conversation history from a JSON string.
    pub async fn set_messages(&mut self, json: &str) -> Result<()> {
        let api = self.instance.strands_agent_api();
        let args = bindings::exports::strands::agent::api::SetMessagesArgs {
            json: json.to_string(),
        };
        api.agent()
            .call_set_messages(&mut self.store, self.wit_agent, &args)
            .await
    }
}

/// The collected result of an agent invocation.
#[derive(Debug, Clone)]
pub struct AgentResult {
    /// The full text produced by the agent.
    pub text: String,
    /// Why the agent stopped.
    pub stop_reason: StopReason,
    /// Optional token usage information.
    pub usage: Option<Usage>,
    /// Optional latency metrics.
    pub metrics: Option<Metrics>,
}

/// If the model config targets Bedrock and has no explicit credentials, try to
/// resolve them from env vars or `~/.aws/credentials` and inject them into the config.
fn inject_aws_credentials(config: Option<ModelConfig>) -> Option<ModelConfig> {
    match config {
        Some(ModelConfig::Bedrock(mut bc)) if bc.access_key_id.is_none() => {
            if let Some((key_id, secret, token)) = resolve_aws_credentials() {
                bc.access_key_id = Some(key_id);
                bc.secret_access_key = Some(secret);
                bc.session_token = token;
            }
            Some(ModelConfig::Bedrock(bc))
        }
        // No model config = default Bedrock. Construct one with resolved credentials.
        None => {
            if let Some((key_id, secret, token)) = resolve_aws_credentials() {
                Some(ModelConfig::Bedrock(BedrockConfig {
                    model_id: String::new(), // empty = let the SDK use its default
                    region: None,
                    access_key_id: Some(key_id),
                    secret_access_key: Some(secret),
                    session_token: token,
                    additional_config: None,
                }))
            } else {
                None
            }
        }
        other => other,
    }
}

/// Try env vars first, then fall back to ~/.aws/credentials.
fn resolve_aws_credentials() -> Option<(String, String, Option<String>)> {
    if let (Ok(key_id), Ok(secret)) = (
        std::env::var("AWS_ACCESS_KEY_ID"),
        std::env::var("AWS_SECRET_ACCESS_KEY"),
    ) {
        let token = std::env::var("AWS_SESSION_TOKEN").ok();
        return Some((key_id, secret, token));
    }

    let home = std::env::var_os("HOME")?;
    let creds_path = std::path::PathBuf::from(home).join(".aws/credentials");
    let contents = std::fs::read_to_string(&creds_path).ok()?;
    let profile = std::env::var("AWS_PROFILE").unwrap_or_else(|_| "default".into());
    parse_aws_profile(&contents, &profile)
}

/// Minimal INI parser: extract credentials from a named profile section.
fn parse_aws_profile(contents: &str, profile: &str) -> Option<(String, String, Option<String>)> {
    let header = format!("[{profile}]");
    let mut in_section = false;
    let mut key_id = None;
    let mut secret = None;
    let mut token = None;

    for line in contents.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_section = trimmed == header;
            continue;
        }
        if !in_section {
            continue;
        }
        if let Some((k, v)) = trimmed.split_once('=') {
            match k.trim() {
                "aws_access_key_id" => key_id = Some(v.trim().to_string()),
                "aws_secret_access_key" => secret = Some(v.trim().to_string()),
                "aws_session_token" => token = Some(v.trim().to_string()),
                _ => {}
            }
        }
    }

    Some((key_id?, secret?, token))
}
